### ISSUE TITLE
Support for IAM Roles

### ISSUE THREAD

**Issue by gpjonesii** [s3-wagon-private/s3-wagon-private#18]
Support for IAM roles would be huge, although it would make sense to use aws-sdk instead of jets3t. Jets3t doesn't include IAM support, but aws-sdk makes it easy.

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html

**Comment by anthcourtney** [comment]
+1 to this, especially support for IAM instance roles.

**Comment by laurio** [comment]
+1 to that, would be very useful.

**Comment by timvisher** [comment]
Turns out jets3t [does support this](https://bitbucket.org/jmurty/jets3t/issues/163/provide-support-for-aws-iam-instance-roles)?

**Comment by timvisher** [comment]
Good to note that s3-wagon-private is _no longer based_ on jets3t.

**Comment by timvisher** [comment]
@danielcompton @technomancy Am I reading this wrong? It looks like with the latest versions of the aws-maven project, this project becomes entirely unnecessary? 

[This](https://github.com/spring-projects/aws-maven/blob/ce6a4ffbd8a59029ebe147124ac2d7ff1a7afd18/src/main/java/org/springframework/build/aws/maven/SimpleStorageServiceWagon.java#L77-L88) Provides a wagon for s3 buckets that supports both private and public buckets at `s3:/` urls using everything from env var to system property to ec2 iam instance metadata.

**Comment by danielcompton** [comment]
@timvisher that seems very likely. Phil has always said he wished this project didn't need to exist, and wished the other projects allowed private repos so this one didn't need to exist.

**Comment by timvisher** [comment]
@danielcompton One reason this project might still need to exist is the support for GPG encrypted credentials, if that's something people want.

**Comment by danielcompton** [comment]
1.3.0 supports native AWS provider chains, I think this can be closed now.
