### ISSUE TITLE
S3 client side encryption support

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [s3-wagon-private/s3-wagon-private#27]
Option 2: Using a Client-Side Master Key

http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingClientSideEncryption.html

**Comment by danielcompton** [comment]
@Andrei-Pozolotin this looks interesting, but is probably a bit out of the scope of my time and abilities to work on at the moment. I'd be happy to consider a PR though. Also FYI, I am also looking at the other Maven S3 wagon projects and what it would take to deprecate this project to move to one of them. I'm not sure when or if that will happen, but keep that in mind.

**Comment by Andrei-Pozolotin** [comment]
OK, I see.

I choose to PR encryption into big old ugly Kuali
https://github.com/jcaddel/maven-s3-wagon/pull/21

See if you want to back port that here.

**Comment by danielcompton** [comment]
Closing for now as out of scope, though if someone is willing to provide a PR I could be interested (talk to me first though!).
