### ISSUE TITLE
Avoid unnecessary calls to mkdirs

### ISSUE THREAD

**Issue by rymndhng** [s3-wagon-private/s3-wagon-private#42]
I'm trying to scope down PUT access to repositories using IAM and I'm having trouble with scoping repository access because `putResource` tries to create empty files at each level, i.e. I'm trying to scope access to `snapshots/com/my/package`, but the plugin tries to write something to `snapshots`.

Is this still a necessity? 

See https://github.com/s3-wagon-private/s3-wagon-private/blob/master/src/main/java/org/springframework/build/aws/maven/PrivateS3Wagon.java#L219

**Comment by danielcompton** [comment]
I don't have a ton of time to work on this at the moment, but am happy to take a patch if you find something that can reduce the scope of permissions that still works.

**Comment by rymndhng** [comment]
Will do

**Comment by rymndhng** [comment]
@danielcompton bump if you have a chance to review the PR :)

**Comment by danielcompton** [comment]
Merged it now, I've released 1.3.1-alpha2 with your changes in them.

**Comment by rymndhng** [comment]
Thanks, I'll give it a spin!
