### ISSUE TITLE
Error with S3 bucket in London (eu-west-2)

### ISSUE THREAD

**Issue by thatismatt** [s3-wagon-private/s3-wagon-private#46]
When I try to deploy to an S3 bucket in London I get the following output:

```
Created /home/matt/dev/xxx/target/xxx-0.0.1.jar
Wrote /home/matt/dev/xxx/pom.xml
Could not transfer artifact org.xxx:xxx:jar:0.0.1 from/to xxx-xxx (s3p://xxx/repo/): 'eu-west-2' is not a valid location constraint
Sending org.xxx/xxx/0.0.1/xxx-0.0.1.pom 
    to s3p://xxx/repo/
Failed to deploy artifacts: Could not transfer artifact org.xxx:xxx:jar:0.0.1 from/to xxx (s3p://xxx/repo/): 'eu-west-2' is not a valid location constraint
```
(company details redacted)

After this my S3 bucket has the .pom, .pom.md5 and .pom.sha1 files but no .jar, .jar.md5 or .jar.sha1.

By comparison changing to a bucket in Ireland (eu-west-1) works great for me.

**Comment by sheelc** [comment]
@thatismatt Can you try 1.3.1-alpha2? 

In PR #41 the code has been updated to determine the region from the official AWS Java SDK region provider chain which should work for newer regions (like eu-west-2). 

You should be able to specify the region from env var (`AWS_REGION`), java system property (`aws.region`), aws profile, or instance metadata. The default region provider chain isn't that well documented, but the code for the default provider is [here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/regions/DefaultAwsRegionProviderChain.java).

**Comment by thatismatt** [comment]
For referrence, originally I was using 1.3.0.

I just tried with 1.3.1-alpha2, I now get a different error:

```
$ lein deploy xxx-repo
Created /home/matt/dev/xxx/target/xxx-0.0.2.jar
Wrote /home/matt/dev/xxx/pom.xml
Could not transfer artifact org.xxx:xxx:jar:0.0.2 from/to xxx-repo (s3p://xxx/repo/): Cannot create enum from eu-west-2 value!
Sending org/xxx/xxx/0.0.2/xxx-0.0.2.pom 
    to s3p://xxx/repo/
Failed to deploy artifacts: Could not transfer artifact org.xxx:xxx:jar:0.0.2 from/to xxx-repo (s3p://xxx/repo/): Cannot create enum from eu-west-2 value!
```

Hope this is useful. Thanks, Matt

**Comment by thatismatt** [comment]
I've dug around a bit, and it appears that the issue occurs because `com.amazonaws.regions.Regions/fromName` throws an `IllegalArgumentException` for "eu-west-2" in version 1.11.28 of com.amazonaws/aws-java-sdk-s3 "1.11.28". Looking at the diff for PR #41 it looks like that is where the issue was introduced, because the call to `Regions/fromName` is actually inside the catch block that was introduced.

For reference:
```
(com.amazonaws.regions.Regions/fromName "eu-west-2")
IllegalArgumentException Cannot create enum from eu-west-2 value!  com.amazonaws.regions.Regions.fromName (Regions.java:74)
```

I updated the version of the aws sdk used in s3-wagon-private to the latest version, and the problem goes away.

What remains a mystery to me is why are the .pom files uploaded but the .jar files fail? Are there different code paths for these different file types?

**Comment by sheelc** [comment]
@thatismatt Excellent, sounds like you were able to get it to work. It looks like `eu-west-2` was introduced to the AWS SDK in 1.11.67 and as you mentioned we're still on 1.11.28. Probably time to upgrade that dependency as AWS keeps releasing new regions (but the region list is essentially hardcoded in the SDK).

Uploading the .pom files and not the .jar files sounds a bit odd to me. I believe all resources are written through [putResource](https://github.com/s3-wagon-private/s3-wagon-private/blob/master/src/main/java/org/springframework/build/aws/maven/PrivateS3Wagon.java#L215). Are we sure that the .pom files were uploaded? The error output posted above is a bit ambiguous as to if the .pom files were successfully written. It might be worth double checking if the .pom files actually exist in the bucket without the .jar files.

**Comment by thatismatt** [comment]
Are you likely to upgrade that dependency soon? Would you accept a patch for the change? Would you jump straight to the latest version (1.11.141) of the AWS SDK?

RE: the pom uploads, here is the content of a shell session where the S3 bucket was initially empty:

```
$ aws s3 ls s3://xxx-maven/
$ lein deploy xxx-repo
Created /home/matt/dev/xxx/target/xxx-0.0.0.jar
Wrote /home/matt/dev/xxx/pom.xml
Could not transfer artifact org.xxx:xxx:jar:0.0.0 from/to xxx-repo (s3p://xxx-maven/repo/): Cannot create enum from eu-west-2 value!
Sending org/xxx/xxx/0.0.0/xxx-0.0.0.pom 
    to s3p://xxx-maven/repo/
Failed to deploy artifacts: Could not transfer artifact org.xxx:xxx:jar:0.0.0 from/to xxx-repo (s3p://xxx-maven/repo/): Cannot create enum from eu-west-2 value!
$ aws s3 ls s3://xxx-maven/repo/org/xxx/xxx/0.0.0/
2017-06-06 13:49:25       2440 xxx-0.0.0.pom
2017-06-06 13:49:25         32 xxx-0.0.0.pom.md5
2017-06-06 13:49:25         40 xxx-0.0.0.pom.sha1
```

So yes, it looks like the pom files are uploaded but the jars aren't. Very strange...

Hope this is useful,
Matt

PS - Apologies for the delayed reply I've been on holiday.

**Comment by sheelc** [comment]
A patch sounds great. We typically just go to the latest AWS SDK and try to make sure there aren't any dependency conflicts (oftentimes from Jackson).

Thanks for double checking on the .pom files. Very surprising that those .pom files made it up to the bucket. I did another initial check to the underlying [AbstractWagon](https://github.com/spring-projects/aws-maven/blob/master/src/main/java/org/springframework/build/aws/maven/AbstractWagon.java) and it looks like everything does indeed only use `putResource`. Perhaps there is a different code path for the two uploads but we'd have to dig deeper. I won't be able to get to that for a bit but sounds like at least everything is working with the later SDK.

**Comment by leourbina** [comment]
I'm having exactly the same issue here, except that in my case it complains about the region 'us-east-2'. Here's the output when trying to deploy to a private repo:

```
Created /Users/leo/code/xxx/target/z-0.1.2.jar
Wrote /Users/leo/code/xxx/pom.xml
Could not transfer artifact xxx:xxx:jar:0.1.2 from/to private (s3p://maven.company.io/releases): Cannot create enum from us-east-2 value!
Sending xxx/xxx/0.1.2/xxx-0.1.2.pom
    to s3p://maven.company.io/releases/
Failed to deploy artifacts: Could not transfer artifact xxx:xxx:jar:0.1.2 from/to compt (s3p://maven.company.io/releases): Cannot create enum from us-east-2 value!
```

I also see the same behavior where the poms actually make it to the bucket, but the jar does not. I'm using version '1.3.1-aplha2' of s3-wagon-private. Prior to this I tried using '1.3.0', and that was causing a similar issue:

```
Created /Users/leo/code/xxx/target/xxx-0.1.2.jar
Wrote /Users/leo/code/xxx/pom.xml
Could not transfer artifact xxx:xxx:jar:0.1.2 from/to private (s3p://maven.company.io/releases): 'us-east-2' is not a valid location constraint
Sending xxx/xxx/0.1.2/xxx-0.1.2.pom
    to s3p://maven.company.io/releases/
Failed to deploy artifacts: Could not transfer artifact xxx:xxx:jar:0.1.2 from/to company (s3p://maven.company.io/releases): 'us-east-2' is not a valid location constraint
```

Any help to get this to work would be greatly appreciated!

**Comment by leourbina** [comment]
I tried upgrading to the latest version of the aws SDK (1.11.184) and that works. I have opened a PR here https://github.com/s3-wagon-private/s3-wagon-private/pull/49/files
