### ISSUE TITLE
Documentation updates for recommended versions

### ISSUE THREAD

**Issue by rymndhng** [s3-wagon-private/s3-wagon-private#56]
We should re-write the README.md to help folks using this. They're tripped up when the docs recommend version `1.3.0`.

In the updated docs, we should probably help users fix their common issues, for example:

- If they're using leiningen >= 2.8.0 then use 1.3.1-alpha3
- If they're using leiningen <= 2.8.0 then use 1.3.1 (but they should *really* update)
- if they're using another build system (maven, etc), they should use 1.3.1-alpha3

**Comment by danielcompton** [comment]
I've released 1.3.1 and updated the docs for this, does that fix the problems you've got here?

**Comment by rymndhng** [comment]
I think so. Thanks!

**Comment by danielcompton** [comment]
Thanks! I've also added you as a committer if you'd like to be one.

**Comment by rymndhng** [comment]
Sure! That’s be awesome, thanks!
