### ISSUE TITLE
private wagon repository not working for leiningen plugins

### ISSUE THREAD

**Issue by ktsujister** [s3-wagon-private/s3-wagon-private#57]
Hi,

I've been having trouble using s3 private repository for my local plugins.

# steps to reproduce.
1. add your private plugin to `:plugins` within `project.clj`.

```clj
:plugins [[s3-wagon-private "1.3.1" :exclusions [commons-logging]]
          [lein-myplugin/lein-myplugin "0.0.1"]]
```

2. add your private repositories to `:repositories` or `:plugin-repositories`

```clj
:repositories [["private" {:url "s3p://my-repository-bucket/repository/" :no-auth true}]]
```
or
```clj
:plugin-repositories [["private" {:url "s3p://my-repository-bucket/repository/" :no-auth true}]]
```

3. lein deps
```
Could not transfer artifact lein-myplugin:lein-myplugin:pom:0.0.1 from/to private (s3p://my-repository-bucket/repository/): No connector available to access repository private (s3p://my-repository-bucket/repository/) of type default using the available factories FileRepositoryConnectorFactory, WagonRepositoryConnectorFactory
This could be due to a typo in :dependencies or network issues.
```

# version
`Leiningen 2.7.1`
`s3-wagon-private "1.3.1"` as mentioned above.

# current workaround
For now, I'm working around this issue by adding above mentioned plugin to `:dependencies` first, and getting it downloaded, and then moving it to `:plugins`, but it would be great if this just works.

**Comment by danielcompton** [comment]
Hi @ktsujister this is a known issue for plugins. Leiningen needs to resolve the plugins before it loads them, but it can't resolve the plugins in your private S3 repo without loading the S3 wagon plugin, which it can't do until it resolves all of the plugins (and so-on).

You can see more info on this at https://groups.google.com/forum/#!msg/clojure/LIgQtK9SbkE/yjxgVFOebK8J and http://librelist.com/browser//leiningen/2012/8/29/plugins-can-t-be-on-s3/#648e7f85c85df8f7248fc9365693c20c.

You will probably need to use an HTTP based Maven wagon to access your plugins. You can deploy them to Clojars if they are not sensitive, or use a private Maven repository.

**Comment by ktsujister** [comment]
Thanks for the reply!
I'll try things mentioned in the thread you mentioned.

I'll close this issue, as it's not particularly this plugin's fault.

**Comment by ktsujister** [comment]
Here's how I got it to work with @technomancy 's suggestion from above mentioned thread.

1. Only have `s3-wagon-private` in `:plugins`.
```clj
 :plugins [[s3-wagon-private "1.3.1" :exclusions [commons-logging]]]
```

2. add myplugin to `:profiles`, within `project.clj`.
```clj
 :profiles {:myplugin {:plugins [[lein-myplugin/lein-myplugin "0.0.1"]]}}
```

3. adding aliases
```clj
 :aliases {"myplugin" ["with-profile" "myplugin" "myplugin"]}
```
