### ISSUE TITLE
Can s3-wagon-private be published to maven central?

### ISSUE THREAD

**Issue by rymndhng** [s3-wagon-private/s3-wagon-private#58]
I'm wondering what it takes to get this up on maven central. We've found this tremendously useful for Java projects as well. I suppose it doesn't change a whole lot other than improving discoverability perhaps and also removing the need to add this to the `pom.xml`.

```
     <pluginRepositories>
       <pluginRepository>
         <id>clojars.org</id>
         <name>Clojars Repository</name>
         <url>http://clojars.org/repo</url>
       </pluginRepository>
     </pluginRepositories>

```

**Comment by danielcompton** [comment]
This is a good idea, though we'll probably have to change the group-id to something that we 'own'. Happy for you to take the lead on this, or I'll get to it at some point.

**Comment by rymndhng** [comment]
I don't have an idea of what's involved but I can definitely start looking at what may be needed to get this done. Does this look like the right place to start? http://central.sonatype.org/pages/requirements.html

**Comment by rymndhng** [comment]
I've started this process in this ticket: https://issues.sonatype.org/browse/OSSRH-36953

@danielcompton Do you have a username I can attach to the ticket?

**Comment by rymndhng** [comment]
The group has been created: `com.github.s3-wagon-private`. This change to the pom isn't compatible with group-less `s3-wagon-private` on Clojars.

There's two ways forward that I can see this moving forward:
- Publish to maven central using `com.github.s3-wagon-private` and update README/links to point to maven central. Deprecate publishing to Clojars (to reduce complexity of deploying)
- Migrate package in Clojars to use `com.github.s3-wagon-private` as well

Alternatively, we can abandon this to make finding the artifact less confusing.

**Comment by danielcompton** [comment]
Thanks for moving this forward. My username is `danielcompton` in Sonatype JIRA.

Can you explain this one more?

> Alternatively, we can abandon this issue to avoid confusion around where the artifact lives.

Do you mean abandon publishing to Maven Central, or something else?

**Comment by rymndhng** [comment]
That's correct, abandon moving to maven central.

**Comment by rymndhng** [comment]
hey @danielcompton, did you have a chance to think about it?  I'm leaning towards doing nothing because the change in the co-ordinates would create more confusion than the value it brings.

**Comment by danielcompton** [comment]
Yeah I think I agree. Will close this for now, thanks for looking into it though!

**Comment by rymndhng** [comment]
I’ll follow up on the sonatype issue with those folks to close the ticket.
