### ISSUE TITLE
Standardize Snapshot Times

### ISSUE THREAD

**Issue by axrs** [s3-wagon-private/s3-wagon-private#60]
I've noticed when creating snapshots to store on S3, it's appending the current system time for conflicts (or multiple versions).

i.e. `backpack-0.0.1-20180316.004209-7.jar`

This could **possibly** cause an issue when a team is distributed across multiple Timezones (and happen to be working on the same snapshot version).

**Comment by axrs** [comment]
I think you understand my question. I agree they should be UTC.

What I noticed today when snapshotting a library is that it used my system time which is UTC+10. I'll look through my maven config and see if something is incorrectly configured, otherwise I'll raise the issue the the maven team.

**Comment by danielcompton** [comment]
We don't have any control over the snapshot version numbers. I think filing a bug upstream with Maven is probably the best place for this. Thanks!
