### ISSUE TITLE
AWS cross account access of s3 buckets

### ISSUE THREAD

**Issue by sidcarter** [s3-wagon-private/s3-wagon-private#63]
We're trying to use artifacts stored in s3 across different AWS accounts.

The s3 bucket has a policy that allows access from the other AWS accounts (using bucket policy).

We are able to download the files using the AWS CLI commands. During the build using maven, artifacts fail to download.

In the interim, we're using AWS Keys and Secret from the account that has the s3 bucket to solve this problem. Is there something we can do to ensure artifacts from the s3 bucket can be downloaded without using credentials?

An example error:

```
[ERROR] Failed to execute goal on project spring-boot-banana-service-microservice: Could not resolve dependencies for project com.aicure:spring-boot-banana-service-microservice:war:0.1.0: Failed to collect dependencies at com.company:commons-logging-support-tests:jar:1.0.0: Failed to read artifact descriptor for com.company:commons-logging-support-tests:jar:1.0.0: Could not transfer artifact com.company:commons-logging-support-tests:pom:1.0.0 from/to maven-s3-release-repo (s3p://company.com/releases): Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 67981729KHK273; S3 Extended Request ID: tZALiuhmPjY/lahdkahjhfalkdfhlakjhjlkhajdhflaksjd72937492/SNQ=) -> [Help 1]
```

Maven version info:
```
$ mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: /usr/share/maven3
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-137-generic", arch: "amd64", family: "unix"
```

s3-wagon-private version in use:
```
            <groupId>s3-wagon-private</groupId>
            <artifactId>s3-wagon-private</artifactId>
            <version>1.3.1</version>
```

**Comment by danielcompton** [comment]
> Is there something we can do to ensure artifacts from the s3 bucket can be downloaded without using credentials?

I don't quite understand your scenario here, are you saying that it works if you use keys that belong to the same account that owns the bucket, but if you try and access that bucket with keys that belong to a different account then it fails? And you can confirm that you can use the second set of keys via the AWS CLI and S3 downloads work correctly? 

I'm not really sure what would be hindering or helping you here, this library pretty much delegates to the AWS Java SDK for most operations AFAICT.

**Comment by sidcarter** [comment]
@danielcompton I found the issue.

Apparently bucket ACLs don't matter. They work with AWS CLI, but don't work with java consistently. Had to apply bucket policy to s3 to allow access from another account and that fixed the issue.

Apologies for the false alarm. Thanks

**Comment by tomconnors** [comment]
I struggled a bit getting this set up, so for anyone this might help:

You need a policy on the bucket and a policy on a role/user in the other account. 

This is the bucket policy. Replace ACCOUNT_ID with the accessing account's id (not the account that contains the bucket).
``` javascript
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::ACCOUNT_ID:root"
      },
      "Action": [
        "s3:GetObject",
        "s3:GetObjectVersion"
      ],
      "Resource": ["arn:aws:s3:::BUCKET_NAME/PATH_TO_RELEASE_ARTIFACTS/*"]
    },
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::ACCOUNT_ID:root"
      },
      "Action": [
        "s3:ListBucket",
        "s3:GetBucketLocation"
      ],
      "Resource": ["arn:aws:s3:::BUCKET_NAME"]
    }
  ]
}
```
Note that this doesn't lock the release artifacts down to a particular user or role in the accessing account. I haven't figured out how to do that.

This is the accessing account's role/user policy:
``` javascript
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "s3:GetObjectVersion",
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::BUCKET_NAME/PATH_TO_RELEASE_ARTIFACTS/*"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::BUCKET_NAME"
        }
    ]
}
```
