### ISSUE TITLE
Support for credential_process

### ISSUE THREAD

**Issue by jeroenvandijk** [s3-wagon-private/s3-wagon-private#64]
Hi,

We are currently migrating away from hardcoded AWS tokens. Instead we want to use an identity provider everywhere [1]. This is a bit too much too explain here, but this process gets session credentials via a special directive to a proces under `credential_process` in the `~/.aws/credential_file` [2].

This feature is supported by the AWS cli tool, but not by the Java AWS sdk [3]. Therefore it is also not supported by this library. I've extended the current implementation in Amazonica to support this feature and we are currently testing this (https://github.com/mcohen01/amazonica/pull/391).

Would you accept a pull request to support this feature?

[1] E.g. https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers.html
[2] https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes
[3] https://github.com/aws/aws-sdk-java-v2/issues/455

**Comment by danielcompton** [comment]
I would be open to a PR if it didn't involve taking on any extra dependencies. Ideally, it'd be implemented in the Java SDK, but that looks like it's a way off. 

I'm not sure how easy/hard it would be to intercept the credentials provider, but if you're happy to make a PR with some docs then I think this seems reasonable.

Open up a PR with your planned changes early though so I can take a look at it before you do any work on docs.

**Comment by danielcompton** [comment]
> To prevent an extra dependency I wrote a naive, but effective, json parser that deals with the credentials json output of the credential_process

I think you could take a dependency on Jackson as that is already part of the core Java SDK IIRC? The other two bullets look good.

I'm not sure if there are any security issues to think about with `credential_process`? It's coming from the user's config, so I don't think so, but would be worth seeing if the Python SDK does any additional security checks here.

**Comment by danielcompton** [comment]
This is now [available](https://github.com/aws/aws-sdk-java/pull/1835#issuecomment-479566295) in [1.11.489](https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111489-2019-01-24). I haven't looked to see how it works, but it may be that all that is required to get it is to upgrade the version of the SDK that we pull in here.

**Comment by jeroenvandijk** [comment]
@danielcompton Thanks, the new aws-java-sdk update does indeed work. Just tested it.
