### ISSUE TITLE
Avoid overwriting release artefact?

### ISSUE THREAD

**Issue by minhtuannguyen** [s3-wagon-private/s3-wagon-private#67]
Hi, 
does s3-wagon-private have a feature that a release artefact with the same version can not be overwritten?

**Comment by danielcompton** [comment]
Not currently. This is more of a server-side concern than a client-side concern IMO. You could maybe hack it in here: https://github.com/s3-wagon-private/s3-wagon-private/blob/ef248502e325c7dbf881666472cb6cbe610ffaf9/src/main/java/org/springframework/build/aws/maven/PrivateS3Wagon.java#L227, but you'd need to infer whether this was a release version based on the key that you were writing to in S3.

There is also backwards compatibility to consider here, people are almost certainly relying on the existing behaviour to redeploy to the same release version (though that's probably not a great idea).

**Comment by minhtuannguyen** [comment]
@danielcompton I just though, it's maybe a good idea to implement this feature and turn it on with a configuration in the project.clj. Anyway, my question is answered. Thank you so much for your response

**Comment by danielcompton** [comment]
It's not a bad idea at all, just one that I'm unlikely to do myself at the moment. It would also need to be considered carefully, but it definitely could be doable.
