### ISSUE TITLE
Dependency Conflict: duplicate classes "org.apache.commons.logging.LogFactory" in different JARs, have different implementations.

### ISSUE THREAD

**Issue by HelloCoCooo** [s3-wagon-private/s3-wagon-private#68]
Hi, in **s3-wagon-private v1.3.2**,  as shown in the following dependency three extracted from pom.xml, both libraries **org.slf4j:jcl-over-slf4j:1.7.5** and **commons-logging:commons-logging:1.1.3** contain class **org.apache.commons.logging.LogFactory**.  Due to _"first declaration wins"_ loading strategy, only the class included in **org.slf4j:jcl-over-slf4j:1.7.5 could be loaded**, and that in **commons-logging:commons-logging:1.1.3 would be shadowed**.

As a result, **com.amazonaws:aws-java-sdk-s3:jar:1.11.337:compile** has to invoke the methods included in the unexpected version of class **org.apache.commons.logging.LogFactory** belonging to library **org.slf4j:jcl-over-slf4j:1.7.5**, which may cause inconsistent semantic behaviors.

For instance, library **com.amazonaws:aws-java-sdk-s3:jar:1.11.337:compile** actually references method **<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>** in the unexpected class version belonging to **org.slf4j:jcl-over-slf4j:1.7.5** via the following invocation path:

```
<org.springframework.build.aws.maven.PrivateS3Wagon: java.util.List listDirectory(java.lang.String)> D:\testcase\TestProject\s3-wagon-private-master\target\classes
<com.amazonaws.services.s3.AmazonS3Client: com.amazonaws.services.s3.model.ObjectListing listObjects(com.amazonaws.services.s3.model.ListObjectsRequest)> D:\cEnvironment\repository\com\amazonaws\aws-java-sdk-s3\1.11.337\aws-java-sdk-s3-1.11.337.jar
<com.amazonaws.services.s3.AmazonS3Client: void <clinit>()> D:\cEnvironment\repository\com\amazonaws\aws-java-sdk-s3\1.11.337\aws-java-sdk-s3-1.11.337.jar
<org.apache.commons.logging.LogFactory: org.apache.commons.logging.Log getLog(java.lang.Class)> D:\cEnvironment\repository\org\slf4j\jcl-over-slf4j\1.7.5\jcl-over-slf4j-1.7.5.jar
<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>

```
By further analyzing, the expected callee **<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>** defined in the shadowed class version of **commons-logging:commons-logging:1.1.3**, have different implementations from the actual callees with the same signatures (same method names, same paremeters) included in the unexpected (but actual loaded) version of class belonging to **org.slf4j:jcl-over-slf4j:1.7.5**, which leads to different behaviors.

### Solution:
There are two solutions can be adopted to solve this dependency conflict issue:
1. Adjust the declaration order of **org.slf4j:jcl-over-slf4j:1.7.5** and **commons-logging:commons-logging:1.1.3** in pom,xml to load class  **org.apache.commons.logging.LogFactory** in **commons-logging:commons-logging:1.1.3**.

2. Make **commons-logging:commons-logging:1.1.3** as the direct dependency in the dependency tree.

**Dependency tree---**
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ s3-wagon-private ---
[INFO] s3-wagon-private:s3-wagon-private:jar:1.3.2
[INFO] +- org.springframework.build:aws-maven:jar:4.8.0.RELEASE:compile
[INFO] |  +- ch.qos.logback:logback-classic:jar:1.0.12:compile
[INFO] |  |  +- ch.qos.logback:logback-core:jar:1.0.12:compile
[INFO] |  |  \- (org.slf4j:slf4j-api:jar:1.7.4:compile - omitted for conflict with 1.7.5)
[INFO] |  +-**_org.slf4j:jcl-over-slf4j:jar:1.7.5:compile_**
[INFO] |  |  \- (org.slf4j:slf4j-api:jar:1.7.5:compile - omitted for conflict with 1.7.4)
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.5:compile
[INFO] +-com.amazonaws:aws-java-sdk-s3:jar:1.11.337:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-kms:jar:1.11.337:compile
[INFO] |  |  +- (com.amazonaws:aws-java-sdk-core:jar:1.11.337:compile - omitted for duplicate)
[INFO] |  |  \- (com.amazonaws:jmespath-java:jar:1.11.337:compile - omitted for duplicate)
[INFO] |  +- com.amazonaws:aws-java-sdk-core:jar:1.11.337:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.5:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.9:compile
[INFO] |  |  |  +- **_(commons-logging:commons-logging:jar:1.2:compile - omitted for conflict with 1.1.3)_**
[INFO] |  |  |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.6.7:compile
[INFO] |  |  \- joda-time:joda-time:jar:2.8.1:compile
[INFO] |  \- com.amazonaws:jmespath-java:jar:1.11.337:compile
[INFO] +- org.apache.maven.wagon:wagon-provider-api:jar:2.4:provided
[INFO] |  \- org.codehaus.plexus:plexus-utils:jar:3.0.8:provided
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.6.7:compile
[INFO] \- com.fasterxml.jackson.core:jackson-databind:jar:2.6.7.1:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.0:compile
[INFO]    \- (com.fasterxml.jackson.core:jackson-core:jar:2.6.7:compile - omitted for duplicate)

Thanks!
Best regards,
Coco

**Comment by HelloCoCooo** [comment]
Code snippet of **<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>** in **org.slf4j:jcl-over-slf4j:jar:1.7.5** (loaded version):
![01](https://user-images.githubusercontent.com/46306510/55382291-e55b6a80-5557-11e9-82dd-b7a28b105619.png)



Code snippet of **<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>** in **commons-logging:commons-logging:1.1.3** (shadowed but expected to invoke method):
![02](https://user-images.githubusercontent.com/46306510/55382294-e9878800-5557-11e9-8d0d-2814cf62061f.png)
![03](https://user-images.githubusercontent.com/46306510/55382303-edb3a580-5557-11e9-8476-a552be7de865.png)
![04](https://user-images.githubusercontent.com/46306510/55382312-f0ae9600-5557-11e9-8edd-11a7e662b84f.png)
![05](https://user-images.githubusercontent.com/46306510/55382319-f3a98680-5557-11e9-8bad-e6a9de897b49.png)
![06](https://user-images.githubusercontent.com/46306510/55382552-834f3500-5558-11e9-9447-dcb39ca7302b.png)

Method **<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>** included in **commons-logging:commons-logging:1.1.3** deals with completely different cases, which changes the control flows and data flows. So being forced to use this method in  **org.slf4j:jcl-over-slf4j:jar:1.7.5** may lead to inconsisitent semantic behaviors.

**Comment by HelloCoCooo** [comment]
May I pull a request to fix it? 8)

Thanks again.

**Comment by danielcompton** [comment]
Happy to look at a PR, there's a lot in your issue and comments, but possibly a PR would make it clearer?

**Comment by danielcompton** [comment]
I don't think there is actually any issue here. https://github.com/s3-wagon-private/s3-wagon-private/pull/69#issuecomment-506078346
