### ISSUE TITLE
Signature V2 auth will be deprecated on June 24, 2019 

### ISSUE THREAD

**Issue by jhallen978** [s3-wagon-private/s3-wagon-private#72]
This plugin will be unsupported in 3 weeks as AWS is switching to supporting only Signature V2 authentication on June 24, 2019.

Currently only a few regions support Signature V2, regions released before 2014.

**Comment by sheelc** [comment]
@jhallen978 Thanks for the heads up on this deprecation.

The [documentation on upgrading to Signature v4](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html#UsingAWSSDK-sig2-deprecation) seems to indicate that as long as we are using a recent version of the SDK, support for Signature v4 should already be present/in use. 

It looks like we're currently on 1.11.337 and the current is 1.11.564. Based on someone using the China region (from closed issue https://github.com/s3-wagon-private/s3-wagon-private/issues/39), which only supports v4, I venture a guess that our SDK might be a late enough version for everything to work as expected.

Have you noticed anything in particular that indicates incompatibility with Signature v4, or some way to demonstrate that our requests are currently occurring over Signature v2?

**Comment by danielcompton** [comment]
Will close this for now, but happy to reopen if there is something we're missing.
