### ISSUE TITLE
1.3.3 not released to Clojars

### ISSUE THREAD

**Issue by jeroenvandijk** [s3-wagon-private/s3-wagon-private#75]
I want to use version `1.3.3` for the STS feature (thanks!), but it isn't released on Clojars yet. I'm fetching it via `-SNAPSHOT` now (`[s3-wagon-private "1.3.3-20190626.232501-1"]` to be precise)

**Comment by danielcompton** [comment]
I've just released 1.3.3 now. Thanks!
