### ISSUE TITLE
Deployment failur

### ISSUE THREAD

**Issue by abstractalchemist** [s3-wagon-private/s3-wagon-private#81]
When running
```
lein deploy <s3 deploy target>
```
I receive the following error
```
Failed to deploy artifacts: Could not transfer artifact mil.mhpcc.portal.clj:portal-aot-common:jar:3.0.0.4 from/to s3.release (s3p://panacea-artifacts/releases): unknown signer type: AWSS3V4SignerType
```
I am deploy from a container running on AWS Codebuild.  The container has role permissions that include read/write on the target bucket.  

When running a native maven deployment, I use the plugin at
https://github.com/seahen/maven-s3-wagon

and it is able to deploy to the target s3 bucket in the previously described environment.

**Comment by danielcompton** [comment]
Can you share your full config and versions? This could be a version conflict with other AWS libraries.

**Comment by abstractalchemist** [comment]
Never mind, it must have been a version conflict because now it seems to have worked.  For the record, when I was having the problem, my plugins section looked liked this
```
:plugins 
 [ [ com.github.seahen/maven-s3-wagon "1.3.1" ] 
 [ s3-wagon-private "1.3.4"] ]
```

removing the maven-s3-wagon plugin and having only the s3-wagoon-private plugin seems to have solved the problem.
